/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CancellationAndRefundRouteImport } from './routes/cancellation-and-refund'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as KeepAliveRouteImport } from './routes/keep-alive'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ShippingAndDeliveryRouteImport } from './routes/shipping-and-delivery'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationAndRefundRoute = CancellationAndRefundRouteImport.update({
  id: '/cancellation-and-refund',
  path: '/cancellation-and-refund',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepAliveRoute = KeepAliveRouteImport.update({
  id: '/keep-alive',
  path: '/keep-alive',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingAndDeliveryRoute = ShippingAndDeliveryRouteImport.update({
  id: '/shipping-and-delivery',
  path: '/shipping-and-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cancellation-and-refund': typeof CancellationAndRefundRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/keep-alive': typeof KeepAliveRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-and-delivery': typeof ShippingAndDeliveryRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cancellation-and-refund': typeof CancellationAndRefundRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/keep-alive': typeof KeepAliveRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-and-delivery': typeof ShippingAndDeliveryRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cancellation-and-refund': typeof CancellationAndRefundRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/keep-alive': typeof KeepAliveRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-and-delivery': typeof ShippingAndDeliveryRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cancellation-and-refund'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/keep-alive'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/shipping-and-delivery'
    | '/terms-and-conditions'
    | '/shop/$slug'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cancellation-and-refund'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/keep-alive'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/shipping-and-delivery'
    | '/terms-and-conditions'
    | '/shop/$slug'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cancellation-and-refund'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/keep-alive'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/shipping-and-delivery'
    | '/terms-and-conditions'
    | '/shop/$slug'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CancellationAndRefundRoute: typeof CancellationAndRefundRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  KeepAliveRoute: typeof KeepAliveRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ShippingAndDeliveryRoute: typeof ShippingAndDeliveryRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-and-refund': {
      id: '/cancellation-and-refund'
      path: '/cancellation-and-refund'
      fullPath: '/cancellation-and-refund'
      preLoaderRoute: typeof CancellationAndRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keep-alive': {
      id: '/keep-alive'
      path: '/keep-alive'
      fullPath: '/keep-alive'
      preLoaderRoute: typeof KeepAliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-and-delivery': {
      id: '/shipping-and-delivery'
      path: '/shipping-and-delivery'
      fullPath: '/shipping-and-delivery'
      preLoaderRoute: typeof ShippingAndDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CancellationAndRefundRoute: CancellationAndRefundRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  KeepAliveRoute: KeepAliveRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ShippingAndDeliveryRoute: ShippingAndDeliveryRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
